# default profile settings
spring:
  profiles:
    active: local

#Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
    # Swagger의 OpenAPI 명세를 제공하는 경로 설정
  swagger-ui:
    path: /swagger-ui.html
    # Swaggerd UI 표시할 URL 경로 설정
    display-request-duration: true # 요청이 안료되는 데 걸린 시간 표시 여부
    operations-sorter: method # 메서드 이름 기준으로 API 정렬
  cors:
    enabled: true

---

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: your_very_long_and_secure_secret_key_that_is_32_bytes_or_more
  accessExpirationTime: 3600000
  refreshExpirationTime: 604800000

cloud:
  aws:
    access-key: ${AWS_ACCESS_KEY:default-access-key}
    secret-key: ${AWS_SECRET_KEY:default-secret-key}
    region: ${AWS_REGION:ap-northeast-2}
    bucket: ${AWS_BUCKET:default-bucket}

server:
  tomcat:
    max_swallow-size: -1
    max-http-form-post-size: -1

---
# DB-JPA Global settig
spring:
  #MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sajang_db
    username: sajang_user
    password: sajang_password
  sql:
    init:
      mode: never
  #JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
---
spring:
  security:
    oauth2:
      client:
        registration:
          # 여기서 'kakao'는 임의의 식별자(registrationId)입니다.
          # 다른 제공자(google, naver 등)를 추가할 수 있습니다.
          kakao:
            client-id: ${KAKAO_REST_API_KEY}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao" # 보통 이 값을 그대로 사용합니다.
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 60MB #들여쓰기 잘하세요

---
#local profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${local.db.url}
    username: ${local.db.username}
    password: ${local.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      use_sql_comments: true
      default_batch_fetch_size: 1000

---
#develop profile
spring:
  config:
    activate:
      on-profile: develop
  datasource:
    url: ${aws.db.url}
    username: ${aws.db.username}
    password: ${aws.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      use_sql_comments: true
      default_batch_fetch_size: 1000
