# default profile settings
spring:
  profiles:
    active: local

# Swagger
springdoc:
  swagger-ui:
    path: /swagger
    display-request-duration: true
  api-docs:
    enabled: true
    path: /v3/api-docs
  cors:
    enabled: true

---

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: your_very_long_and_secure_secret_key_that_is_32_bytes_or_more
  accessExpirationTime: 3600000
  refreshExpirationTime: 604800000

---
# DB-JPA Global settig
spring:
  #MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sajang_db
    username: sajang_user
    password: sajang_password
  sql:
    init:
      mode: never
  #JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
---
# Swagger
springdoc:
  swagger-ui:
    path: /swagger
  cache:
    disabled: true
  use-fqn: true
  packages-to-scan: likelion13gi.demoXS
---
spring:
  security:
    oauth2:
      client:
        registration:
          # 여기서 'kakao'는 임의의 식별자(registrationId)입니다.
          # 다른 제공자(google, naver 등)를 추가할 수 있습니다.
          kakao:
            client-id: ${KAKAO_REST_API_KEY}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao" # 보통 이 값을 그대로 사용합니다.
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id